### ISSUE TITLE
KafkaChannel .status.conditions.reason should be "one-word, CamelCase representation of the category of cause of the current status"

### ISSUE THREAD

**Issue by maschmid** [knative-extensions/eventing-kafka-broker#2232]
**Describe the bug**
Seeing a KafkaChannel with status

```
status:
  conditions:
  - lastTransitionTime: "2022-05-27T14:55:20Z"
    status: Unknown
    type: Addressable
  - lastTransitionTime: "2022-05-27T14:55:20Z"
    status: Unknown
    type: ConfigMapUpdated
  - lastTransitionTime: "2022-05-27T14:55:20Z"
    reason: 'failed to resolve Spec.Delivery.DeadLetterSink: address not set for &ObjectReference{Kind:Parallel,Namespace:test-iizggqjx,Name:kcmtbkcpar-dls,UID:,APIVersion:flows.knative.dev/v1,ResourceVersion:,FieldPath:,}'              
    status: "False"
    type: ConfigParsed
  - lastTransitionTime: "2022-05-27T14:55:20Z"
    status: "True"
    type: DataPlaneAvailable
  - lastTransitionTime: "2022-05-27T14:55:20Z"
    status: Unknown
    type: ProbeSucceeded
  - lastTransitionTime: "2022-05-27T14:55:20Z"
    reason: 'failed to resolve Spec.Delivery.DeadLetterSink: address not set for &ObjectReference{Kind:Parallel,Namespace:test-iizggqjx,Name:kcmtbkcpar-dls,UID:,APIVersion:flows.knative.dev/v1,ResourceVersion:,FieldPath:,}'              
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-05-27T14:55:20Z"
    reason: Topic knative-messaging-kafka.test-iizggqjx.kcmtbkcpar-kne-trigger created
    status: "True"
    type: TopicReady
```

Per https://github.com/kubernetes/community/blob/4c9ef2d/contributors/devel/sig-architecture/api-conventions.md , 

> In condition types, and everywhere else they appear in the API, Reason is intended to be a one-word, CamelCase representation of the category of cause of the current status, and Message is intended to be a human-readable phrase or sentence, which may contain specific details of the individual occurrence. Reason is intended to be used in concise output, such as one-line kubectl get output, and in summarizing occurrences of causes, whereas Message is intended to be presented to users in detailed status explanations, such as kubectl describe output.

 **Expected behavior**
Error conditions should have single-word CamelCase `reason` with an optional human-readable `message` 

 **To Reproduce**

 **Knative release version**
1.2.3

 **Additional context**
