### ISSUE TITLE
Rename config-kafka-features feature flags to be consistent with eventing core feature flag names

### ISSUE THREAD

**Issue by pierDipi** [knative-extensions/eventing-kafka-broker#3509]
**Problem**

The Kafka feature flag names are not consistent with Eventing core, we're using dots to separate words while eventing core is using a hyphen.

We should rename feature flags in [1] and [2] as follow:

```yaml
  dispatcher-rate-limiter: "disabled"
  dispatcher-ordered-executor-metrics: "disabled"
  controller-autoscaler-keda: "disabled"
  triggers-consumergroup-template: "knative-trigger-{{ .Namespace }}-{{ .Name }}"
  brokers-topic-template: "knative-broker-{{ .Namespace }}-{{ .Name }}"
  channels-topic-template: "knative-messaging-kafka.{{ .Namespace }}.{{ .Name }}"
```

**In the code, we should make sure that we keep parsing the old deprecated feature flag names if the new ones are not present to avoid breaking changes with something like this (for each feature flag):**

```golang
err := configmap.Parse(cm.Data, 
 		asFlag("dispatcher.rate-limiter", &nc.features.DispatcherRateLimiter), 
 		asFlag("dispatcher-rate-limiter", &nc.features.DispatcherRateLimiter), , 
 	)
``` 

[1] https://github.com/knative-extensions/eventing-kafka-broker/blob/main/control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml
[2] https://github.com/knative-extensions/eventing-kafka-broker/blob/7b581b7807df14b27b7100293706da8269c04c45/control-plane/pkg/apis/config/features.go#L79-L90

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Admin

**Exit Criteria**

Feature flags have different names

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

/good-first-issue
