### ISSUE TITLE
Is it possible to install this plugin using knative-operator?

### ISSUE THREAD

**Issue by gilesrapkinb** [knative-extensions/eventing-kafka-broker#3695]
I'm trying to install `knative-eventing` using the operator, with `eventing-kafka-broker` installed via `additionalManifests` in the `KnativeEventing` resource:

```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: 1.13.1
  additionalManifests:
  - URL: https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.13.1/eventing-kafka-controller.yaml
  - URL: https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.13.1/eventing-kafka-broker.yaml
```

However, the operator is throwing an error on install:

*Install failed with message: the version of the manifests ve6b002188068b4caebdba747eda522f465fa1583 of the component kafka-broker-config does not match the target version of the operator CR v1.13.1*

It looks like the operator is blocking on applying the extra manifests because the resources in them have the label `app.kubernetes.io/version: "e6b002188068b4caebdba747eda522f465fa1583"` (It looks like the version label has the git SHA rather than the version tag?). Is this a bug? Or am I trying to use the wrong manifests to install with the operator?
