### ISSUE TITLE
Do delivery specs in broker configs apply to event processing errors as well as delivery failures?

### ISSUE THREAD

**Issue by gilesrapkinb** [knative-extensions/eventing-kafka-broker#3746]
**Describe the bug**

This is more of a question than a bug report. 

I've recently set up Knative eventing with Kafka brokers; one main broker, with another Kafka broker configured as a dead letter sink. Also a delivery spec with retries, exponential backoff etc. configured.

I was trying to test the dead letter sink setup with a test function that always returns a 500 in response to any events. The retry behaviour is not quite what I expected. Events seem to get retried forever instead of the retry count specified in the delivery spec.  

I am able to get events to get sent to the dead letter sink under other scenarios, e.g. setting the test function to timeout, or respond in a way that doesn't conform to the delivery contract (like responding with a 200 without a cloudevent in the response body).

Is a function responding with a 500 error not considered a delivery failure? If not, what is the expected behaviour in this scenario? Is there another way to configure retry/backoff/dead letter behaviour for event processing failures?

 **Expected behavior**

I initially expected the delivery spec to also apply to events that weren't processed successfully by a function that received the event (responded with a 500).

 **To Reproduce**

1. Create 2 kafka based brokers, and configure a delivery policy on the main broker.
    ```yaml
    apiVersion: eventing.knative.dev/v1
    kind: Broker
    metadata:
      annotations:
        eventing.knative.dev/broker.class: Kafka
      labels:
        app: knative-broker
      name: knative-broker
      namespace: default
    spec:
      config:
        apiVersion: v1
        kind: ConfigMap
        name: knative-broker
        namespace: default
      delivery:
        backoffDelay: PT0.5S
        backoffPolicy: exponential
        deadLetterSink:
          ref:
            apiVersion: eventing.knative.dev/v1
            kind: Broker
            name: knative-broker-deadletter
            namespace: default
        retry: 12
    ---
    apiVersion: eventing.knative.dev/v1
    kind: Broker
    metadata:
      annotations:
        eventing.knative.dev/broker.class: Kafka
      labels:
        app: knative-broker
      name: knative-broker-deadletter
      namespace: default
    spec:
      config:
        apiVersion: v1
        kind: ConfigMap
        name: knative-broker
        namespace: default
      delivery:
        backoffDelay: PT0.2S
        backoffPolicy: exponential
        retry: 10
    ```
2. Create a function that always returns a 500 in response to an event, deploy, with a trigger
3. Send a test event to the broker, see it get repeatedly retried and not sent to the dead letter sink

 **Knative release version**

1.13.1

 **Additional context**

N/A
