### ISSUE TITLE
Set client.rack based on availabitly zone

### ISSUE THREAD

**Issue by joke** [knative-extensions/eventing-kafka-broker#3794]
**Problem**

Kafka is rack aware. Clients should specify the [`client.rack`](https://kafka.apache.org/documentation/#consumerconfigs_client.rack). Brockers should specify [`broker.rack`](https://kafka.apache.org/documentation/#brokerconfigs_broker.rack).

AWS sets `broker.rack` to the availability zone. Knative could set the `client.rack` to node label `topology.kubernetes.io/zone`.

Using rack awareness would reduce cross availability zone traffic costs. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

System Operator

**Exit Criteria**

Consumers do set the `client.rack` based on the `topology.kubernetes.io/zone`.

**Comment by Cali0707** [comment]
/remove-lifecycle stale

@pierDipi this seems like a reasonable request, can we discuss design this week on the Eventing call?

**Comment by Cali0707** [comment]
It seems like Strimzi makes this configurable through a spec like:
```
kafka:
  rack
    topologyKey: topology.kubernetes.io/zone
```

IMO, a flag like `kafka-rack-topology-key` in the `config-kafka-features` configmap could make sense here. If present, we could check if there is a label on the node for that, and if there we can use the value to set `client.rack`

**Comment by joke** [comment]
Maybe the `kafka-rack-topology-key` be set to [`topology.kubernetes.io/zone`](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone). After all that's the default annotation.

**Comment by pierDipi** [comment]
We need to use something like this 

```
      containers:
      - name: ...
        image: ...
        env:
        - name: CLIENT_RACK
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['topology.kubernetes.io/zone']
```

We need to figure out what happen when that key doesn't exists and if it doesn't work, maybe we support injecting that env variable but we don't set it by default
