### ISSUE TITLE
Lots of logs with "Resetting the last seen epoch of partition"

### ISSUE THREAD

**Issue by joke** [knative-extensions/eventing-kafka-broker#3881]
**Describe the bug**

The `kafka-channel-receiver` is logging lots these `Resetting the last seen epoch` messages. As far as I understand the problem the client doesn't track the epoch of a topic partition. 

This message is logged about every minute for every partition of every topic.

````yaml
'@timestamp': '2024-05-03T20:24:51.406Z'
'@version': '1'
message: >-
  [Producer clientId=producer-3] Resetting the last seen epoch of partition
  knative-messaging-kafka.demo.sequence-kn-sequence-2-9 to 24 since the
  associated topicId changed from null to 2RdjCRMuRx2ylkDhntN0SA
logger_name: org.apache.kafka.clients.Metadata
thread_name: kafka-producer-network-thread | producer-3
level: INFO
level_value: 20000
````

 **Expected behavior**

If this is expected the log level should be decreased.

 **To Reproduce**

Seems to be happening with [v1.13.0](https://github.com/knative-extensions/eventing-kafka-broker/releases/tag/knative-v1.13.0) and releases before that.

 **Knative release version**

v1.13.0
