### ISSUE TITLE
create Pod kafka-source-dispatcher-0 in StatefulSet kafka-source-dispatcher failed error: Pod "kafka-source-dispatcher-0" is invalid: spec.containers[0].volumeMounts[1].name: Not found: "contract-resources"

### ISSUE THREAD

**Issue by stanislav-pimenov** [knative-extensions/eventing-kafka-broker#4119]
**Describe the bug**

kafka-source-dispatcher stateful set pods are not patched with configmap created

`create Pod kafka-source-dispatcher-0 in StatefulSet kafka-source-dispatcher failed error: Pod "kafka-source-dispatcher-0" is invalid: spec.containers[0].volumeMounts[1].name: Not found: "contract-resources"`

 **Expected behavior**
kafka-source-dispatcher-0 configmap is automatically created for pod number 0
kafka-source-dispatcher-1 configmap is automatically created for pod number 1

 **To Reproduce**
1. Create KafkaSource
2. Check kafka-source-dispatcher stateful set.

 **Knative release version**

1.15.2
1.15.4

 **Additional context**

Issue was already reported a couple of months ago, but no fix was provided.
https://github.com/knative-extensions/eventing-kafka-broker/issues/3995

Istio sidecars are enabled for stateful set

**Comment by pierDipi** [comment]
@stanislav-pimenov are you making any changes to the released YAMLs or just applying them as they are?

Can you share what's the output of this script

```shell
kubectl get namespace knative-eventing -oyaml
kubectl get mutatingwebhookconfiguration pods.defaulting.webhook.kafka.eventing.knative.dev -oyaml
kubectl get pods -n knative-eventing -oyaml
kubectl get statefulsets -n knative-eventing -oyaml
```

**Comment by stanislav-pimenov** [comment]
hi @pierDipi 

Yes, I made a couple of changes.

1. namespace name is changed
2. For kafka-source-dispatcher stateful set: Istio sidecartinjection is enabled  with labels ( module istio-net is installed within serving namespace)
```
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/proxyMemoryLimit: 200m
        sidecar.istio.io/proxyCPULimit: 500Mi
```

Here is the requested output

`kubectl get MutatingWebhookConfiguration pods.defaulting.webhook.kafka.eventing.knative.dev -oyaml`

```
webhooks:
  - name: pods.defaulting.webhook.kafka.eventing.knative.dev
    sideEffects: None
    clientConfig:
      service:
        namespace: clustername-kn-eventing
        name: kafka-webhook-eventing
        path: /pods-defaulting
        port: 443
      caBundle: >-
    reinvocationPolicy: IfNeeded
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ''
        apiVersions:
          - v1
        resources:
          - pods
          - pods/status
        scope: '*'
    matchPolicy: Equivalent
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: knative-eventing
      matchExpressions:
        - key: webhooks.knative.dev/exclude
          operator: DoesNotExist
    admissionReviewVersions:
      - v1
      - v1beta1
    failurePolicy: Fail
    objectSelector:
      matchLabels:
        app.kubernetes.io/kind: kafka-dispatcher
    timeoutSeconds: 2
```

for the rest of the output let me upload as files.

**Comment by pierDipi** [comment]
> 1. namespace name is changed

the namespace name change will cause 

```
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: knative-eventing
      matchExpressions:
        - key: webhooks.knative.dev/exclude
          operator: DoesNotExist
```

to not be evaluated, changing the namespace name can be done but it's not as simple as changing the namespace

**Comment by stanislav-pimenov** [comment]
output for pods (cluster details removed. a little but obfuscated)
https://github.com/stanislav-pimenov/knative-samples/blob/main/kn-eventing-pods.yaml
for statefulset
https://github.com/stanislav-pimenov/knative-samples/blob/main/kn-eventing-statefulset.yaml

As soon as I manually add such volume everything is up and running
```
volumes:
        - name: contract-resources
          configMap:
            name: removeme-config
```

**Comment by pierDipi** [comment]
For you case, you will get the volume automatically on *pod creation* (not update or dangling) if you change the webhook configuration namespace selector to your namespace

```
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: clustername-kn-eventing
      matchExpressions:
        - key: webhooks.knative.dev/exclude
          operator: DoesNotExist
```
