### ISSUE TITLE
Sequence unable to connect to kafka broker using SSL

### ISSUE THREAD

**Issue by eexwhyzee** [knative-extensions/eventing-kafka-broker#4123]
**Describe the bug**
we're trying to set up knative-eventing with a kafka broker (using an external kafka cluster via AWS MSK), sequence, and trigger setup using SSL for client authentication.

So the broker works as expected and has no issues connecting to the external kafka cluster with SSL:
```
❯ kubectl get brokers -n test
NAME           URL                                                                                AGE   READY   REASON
test-broker   http://kafka-broker-ingress.knative-eventing.svc.cluster.local/test/test-broker   96m   True
```

but the sequence (and the underlying KafkaChannels) and the trigger resource are having issues getting created:
```
❯ kubectl get sequences -n test
NAME           URL   AGE    READY     REASON
test-sequence         96m   Unknown   emptyAddress

❯ kubectl get kafkachannels -n test
NAME                         READY   REASON                                                                               URL   AGE
test-sequence-kn-sequence-0   False   Failed to create topic: knative-messaging-kafka.test.test-sequence-kn-sequence-0         96m
test-sequence-kn-sequence-1   False   Failed to create topic: knative-messaging-kafka.test.test-sequence-kn-sequence-1         96m

❯ kubectl get triggers -n test
NAME                          BROKER         SUBSCRIBER_URI   AGE    READY   REASON
test-sequence-trigger   test-broker                    96m   False   Failed to resolve trigger config
```

error message specifically from the sequence resource:
```
Message:               cannot obtain Kafka cluster admin: kafka: client has run out of available brokers to talk to: 3 errors occurred:
                             * unexpected EOF
                             * unexpected EOF
                             * unexpected EOF
```

 **Expected behavior**
both the broker and sequence should be able to connect to the external kafka cluster using SSL for client authentication.

 **To Reproduce**
currently we use the knative operator to configure the `kafka-broker-config` and the `kafka-channel-config`:
```
  apiVersion: operator.knative.dev/v1beta1
  kind: KnativeEventing
  metadata:
    name: knative-eventing
    namespace: knative-eventing
  spec:
    version: 1.13.0
    config:
      kafka-broker-config:
        auth.secret.ref.name: ${TLS_CERT_SECRET}
        default.topic.partitions: "1"
        default.topic.replication.factor: "2"
        bootstrap.servers: ${BOOTSTRAP_BROKERS}
      kafka-channel-config:
        auth.secret.ref.name:  ${TLS_CERT_SECRET}
        default.topic.partitions: "1"
        default.topic.replication.factor: "2"
        bootstrap.servers: ${BOOTSTRAP_BROKERS}
    source:
      kafka:
        enabled: true
```
(auth secret was created these [docs](https://knative.dev/docs/eventing/brokers/broker-types/kafka-broker/#authentication-and-encryption-using-ssl))

broker YAML:
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: test-broker
  namespace: test
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
```

sequence YAML:
```
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: test-sequence
  namespace: test
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
      numPartitions: 1
      replicationFactor: 2
  steps: 
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: step1
        namespace: test
      uri: /step1
     - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: step2
        namespace: test
      uri: /step2
  reply:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: test-broker
      namespace: test
```

trigger YAML:
```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: test-sequence-trigger
  namespace: test
spec:
  broker: test-broker
  filter:
    attributes:
      source: /apis/v1/namespaces/test/containersources/test-new
      type: test.job.created
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: test-sequence
      namespace: test
    uri: /
```

 **Knative release version**
1.13.0

 **Additional context**
So we actually have this setup working and functional on our separate development cluster, but without using SSL since we had a separate dev AWS MSK instance that didn't have client auth enabled for testing initially (so no auth secret was used for the broker/channel configs). We only saw these issues come up once we spun up this setup in a separate environment, with a new k8s cluster and new AWS MSK cluster that has client auth enabled via SSL. Any help would be much appreciated!
