### ISSUE TITLE
[kafka-extension] Tracing for Knative Eventing doesn't work

### ISSUE THREAD

**Issue by sotatek-hungpham5** [knative-extensions/eventing-kafka-broker#4190]
**Describe the bug**
I tried to configure tracing for Kevent, include kafka-extension
The config is:
```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  config-tracing:
          backend: "zipkin"
          # zipkin-endpoint: "http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans"
          zipkin-endpoint: "http://jaeger-collector.monitoring.svc.cluster.local:9411/api/v2/spans"
          sample-rate: "0.1"
          debug: "false"
```
Note that it's the same with Kserving
I've tested with imc broker and it worked well but cannot see anything related to kafka-extension in trace data, for both trace and metrics.

 **Expected behavior**
Can see full trace of eventing application including Kafka extension.

 **Knative release version**
`1.15`
